### ISSUE TITLE
Suggestions for when shrink is more stable

### ISSUE THREAD

**Issue by kohlth** [gigabit101/Shrink#1]
Hi i had some ideas for things in shrink and i wanted to put them here so i dont forget. I do know your still making the current shrink mod more stable so these are ideas for a later date

1. Player tubes
Allows for player travel when shrunk through tubes

2. Tiny barn
By shrinking your animals down you can now fit them into a tiny barn (have to use capture tool to capture then put into the barn) that uses rf to produce stuff like milk, leather, pork, beef, wool, and all other passive farm animal drops
*You can only put ony type of animal in a barn so no mixing animals
*has diffrent modes for what you want to produce (shear for wool and feathers, slaughter for meat/leather, milk for well milk etc)
*max 16 animals per barn

3.Tiny village

Tired of having mobs kill all your villagers or having them take up a ton of space? 

Now with the tiny village you can put your shrunk down villagers into safe and conveinent space so you can trade with them and prevent them from being killed!

4. Tiny player cannons
Launch shunk players from a cannon at maximum yeet force

Thats all.... for now (evil laughter) love the mod Cant wait to see where it goes!

**Comment by gigabit101** [comment]
Both of these sounds like great ideas and I have already had the idea for the tube.
Currently, the Shrink mod will mostly be an API with most of the Core functionality inside of it, As the mod has an API I do plan on adding some of these suggestions into an addon mod for Shrink but not into the base mod.
