### ISSUE TITLE
fov change

### ISSUE THREAD

**Issue by Parilia** [gigabit101/Shrink#10]
After using this mod on the direwolf20 pack I and another on my server have been randomly crouching, at least thats what it looks like for the players perspective. Actually crouching brings your perspective back to normal, this happens whether you have a gui up on screen or not. Restarts have not worked and I see no way that it is another mod.

**Comment by gigabit101** [comment]
I do not change your eye-height unless you are shrunk, I can not think of any other way my mod could be doing this.
I have just taken a look at the handler and can confirm that I do not touch anything + your eye-height would be a LOT lower if this was caused by Shrink

**Comment by Parilia** [comment]
This bug has only happened after using your mod, also happened to another on my server and is a bug others are experiencing.
This has not happened to people on my server who have not used your mod. Would your mod conflict with anything?
