### ISSUE TITLE
[Bug]: Some Mobs from Mods Aren't Shrinkable (1.19.2)

### ISSUE THREAD

**Issue by arlight1** [gigabit101/Shrink#101]
### Describe the bug

It seems some mobs from mods can be shrunk and some can't

### Steps to reproduce

When it works....
1. Left click on Mob like chicken, cow, any of Alex's Mobs with the personal shrinking device
2. Right click with glass bottle to capture
3. Done.

When it doesn't....
1. Left click on a mob like Starbuncle from Ars or Otter from Creatures and Beasts
2. Nothing happens when left-clicked with the device

### Expected behaviour

Appears to function normally on DW 1.20 modpack, see the video at https://youtu.be/tbxTxdFEvuk?si=OFiuQHRY3jJUcX4r&t=1389

Doesn't work on FTB University 1.19.2, however. Anything that can be done to make it work or is it something that started working as of NeoForge 1.20+?

### Version

1.3.5

### Minecraft Version

1.19.2

### ModLoader Version

43.3.5

**Comment by gigabit101** [comment]
They use GekoLib to render their entities, I have added support in newer versions for this but not in 1.19 and I have no plans on backporting these changes

**Comment by arlight1** [comment]
Understood. Thanks for the quick response!
