### ISSUE TITLE
[Bug]: 1.21 Recipe for Personal Shrinking Device not working

### ISSUE THREAD

**Issue by Kevin-Marsh** [gigabit101/Shrink#106]
### Describe the bug

Recipe for Personal Shrinking Device not working. I believe it  is due to the 1.21 minecraft change from the recipes folder to the recipe folder. They just removed the s.

### Steps to reproduce

Try to craft the personal shrinking device

### Expected behaviour

The device should have a recipe.

### Version

N/A

### Minecraft Version

1.21

### ModLoader Version

Neoforge 21.0.51

**Comment by gigabit101** [comment]
whoops, will take a look tonight

**Comment by gigabit101** [comment]
This has now been fixed and a new version is now uploading to CurseForge
