### ISSUE TITLE
[Bug]: u cant shrink urself

### ISSUE THREAD

**Issue by sdasdasdytrgb** [gigabit101/Shrink#107]
### Describe the bug

doesnt work

### Steps to reproduce

dont want to fill this in

### Expected behaviour

dont want to fill this in

### Version

1.21

### Minecraft Version

1.21

### ModLoader Version

Neoforge

**Comment by gigabit101** [comment]
dont want to fill this in

**Comment by LokeYourC3PH** [comment]
He's right though. If you use a command such as 

> /shrink (name) 1

still doesn't really reset and unshrinks you. You cannot open a Personal Shrinking Device until somebody else unshrinks you with one in their hand, which is clearly a bug that needs to be fixed. That, or we need an item that you can unshrink yourself with.

**Comment by gigabit101** [comment]
You can use the shrinking device to unshrink yourself
