### ISSUE TITLE
Shrinking half block without using item

### ISSUE THREAD

**Issue by Jabbathejubjub** [gigabit101/Shrink#11]
Playing with the mod on a server and randomly the camera will shrink by half a block. You can press the crouch button to undo it, but it's relativly frequent

**Comment by gigabit101** [comment]
Managed to track down the issue, It seems to happen when another player joins the server just as an FYI

**Comment by Feliixtc** [comment]
It also seems to happen any time you (even on single player), or anyone else loads from another dimension. I'm not sure if this is basically the same thing as the server join issue you have already tracked.

**Comment by gigabit101** [comment]
1.1.0 Is now released, https://www.curseforge.com/minecraft/mc-mods/shrink_/files/3352335

**Comment by NillerMedDild** [comment]
I've received another report of this, on 1.1.0: https://github.com/NillerMedDild/Enigmatica6/issues/1527#issuecomment-864618200
