### ISSUE TITLE
[Bug]: Hitbox and perspective do not change

### ISSUE THREAD

**Issue by Kiedamon** [gigabit101/Shrink#113]
### Describe the bug

Hitbox and perspective do not change

### Steps to reproduce

1. create new modpack in curse forge
2. add Shrink.
3. Run game
4. use Shrink Remote

### Expected behaviour

Perspective and hitbox change proportionally to size.

### Version

2.0.0.40

### Minecraft Version

1.20.4

### ModLoader Version

Forge 49.1.0

**Comment by gigabit101** [comment]
Unable to reproduce the issue
