### ISSUE TITLE
[Bug]: Missing 1.21.1 tag and Modrinth page

### ISSUE THREAD

**Issue by JohnGoten** [gigabit101/Shrink#117]
### Describe the bug

The Shrink mod's recent 1.21 releases do not include a 1.21.1 tag and cannot be found using third-party launcher, e.g. Prism

### Steps to reproduce

Visit https://www.curseforge.com/minecraft/mc-mods/shrink_/files/all?page=1&pageSize=20 in hopes for a 1.21.1 release of Shrink just to be disappointed by it being tagged as 1.21 only
Or, using the Prism Launcher, press the "Download Mods" button when editing a 1.21.1 (either NeoForge or Fabric, of no matter as it affects both) and search for "Shrink" having selected CurseForge as source.

### Expected behaviour

Minecraft version 1.21 has been widely considered abandoned and not to be used since the introduction of the hotfix 1.21.1
https://www.minecraft.net/en-us/article/minecraft-java-edition-1-21-1
As is effectively any 1.21 mod functions just fine in a 1.21.1 instance, however due to it missing the needed tag, the Shrink mod is nowhere to be found using Prism's (in my case) mod search for easy installation.

On top of that I would highly advise setting up a Modrinth page alongside in order to allow users of the alternative platform to download the mod, especially in context of modpack development. Generally weird for developers to disregard MR when simultaneous uploads aren't too difficult to get up and running.

### Screenshots

![image](https://github.com/user-attachments/assets/1d0489dc-f7fc-4b68-a30e-9cf45572e657)
![image](https://github.com/user-attachments/assets/5cf3e47b-39dd-469a-993b-4d28424ce896)

### Version

-

### Minecraft Version

1.21.1

### ModLoader Version

-

### Additional Information

Given that Shrink received its latest update on November 20th I would have been under the assumption for you to be aware of the situation but it appears as if there are still individuals unaware of what needs to be done which I hope to change with reports like this one (:

**Comment by gigabit101** [comment]
I have updated the tags for 1.21.1, Also Shrink has been available on Modrinth for a little while now https://modrinth.com/mod/shrink
