### ISSUE TITLE
Shrinking or moving with no extra block above you puts you in the crawl position, and your hitbox increases significantly

### ISSUE THREAD

**Issue by Spirevipp** [gigabit101/Shrink#12]
Title, tested with the Direwolf20 1.16 modpack
This is especially noticeable when you have some sort of flight mod (jetpack, angel ring, etc)
any way to prevent the crawl thing when shrunk?

thanks for the great mod! :)

**Comment by gigabit101** [comment]
1.1.0 Is now released, https://www.curseforge.com/minecraft/mc-mods/shrink_/files/3352335
