### ISSUE TITLE
Feature Requests: Grow/Giants? Alice-in-Wonderland (Eat Me/Drink Me)?

### ISSUE THREAD

**Issue by soulhakr** [gigabit101/Shrink#13]
There's a similar mod (PymTech, by Lucraft) that provides functionality to shrink, but also provides an option to grow. The primary reason I haven't been using that mod is the library it uses seems to cause instabilities. Would you be able and/or willing to implement of "Grow-to-Giant-size" feature?

Secondly, would you be willing/able to implement a potion effect or food item which changes one's size (as opposed to a device or piece of tech)? This would allow the mod to fit into more fantasy or magic-themed packs a bit better.

**Comment by gigabit101** [comment]
Sizes will be configurable in the next version of the Mod, The Mod has a full API so adding items to do this would be easy.
