### ISSUE TITLE
Bounding box of shrunk entities doesn't update correctly

### ISSUE THREAD

**Issue by ochotonida** [gigabit101/Shrink#19]
When you shrink or unshrink an entity, their bounding box will retain it's original size until it either moves or collides with another entity.
![image](https://user-images.githubusercontent.com/37985539/110215085-3395e880-7ea8-11eb-93ef-66809e02288c.png)
This also applies to the player if you keep sneaking after using the shrinking device. (in this case, moving or colliding does not update the bounding box)
![image](https://user-images.githubusercontent.com/37985539/110215177-aef79a00-7ea8-11eb-8894-9ada4c749fc2.png)

**Comment by gigabit101** [comment]
1.1.0 Is now released, https://www.curseforge.com/minecraft/mc-mods/shrink_/files/3352335
