### ISSUE TITLE
(Blacklist) Armor stands have a full sized model when shrunk

### ISSUE THREAD

**Issue by ochotonida** [gigabit101/Shrink#20]
Armor stands can be shrunk and unshrunk, however their model does not reflect this
![image](https://user-images.githubusercontent.com/37985539/110215286-3218f000-7ea9-11eb-8302-a0c3a056b587.png)

**Comment by gigabit101** [comment]
👀

**Comment by gigabit101** [comment]
This will need adding to the blacklist, completely forgot that armour stands are living entities

**Comment by ochotonida** [comment]
On a related note, I'd suggest implementing the blacklist using an entity type tag such that other mods can also easily blacklist entities
