### ISSUE TITLE
Eye height is not updated when shrinking and unshrinking an entity twice

### ISSUE THREAD

**Issue by ochotonida** [gigabit101/Shrink#21]
If you shrink and unshrink an entity twice, their eye height will remain at the same position it was when they were shrunk
![image](https://user-images.githubusercontent.com/37985539/110215389-d438d800-7ea9-11eb-8689-f92444b4df65.png)

**Comment by gigabit101** [comment]
This was an issue with how I was storing the data, This has already been fixed in dev

**Comment by gigabit101** [comment]
1.1.0 Is now released, https://www.curseforge.com/minecraft/mc-mods/shrink_/files/3352335
