### ISSUE TITLE
Shrink 1.1.0

### ISSUE THREAD

**Issue by gigabit101** [gigabit101/Shrink#22]
I am currently in the process of rewriting a large chunk of the backend code for Shrink to allow for more options when it comes to entity sizes.

While doing this many bugs have been fixed due.
Currently, this new version is in closed testing and will be released once it's stable.

**Comment by monkeybug34** [comment]
are you looking for testers?

**Comment by skerit** [comment]
@gigabit101 Super! It's such a cool mod. I originally mainly wanted to use it to transport villagers, but all my players love it for shrinking themselves.

**Comment by TheJN101** [comment]
Hey sorry for asking but how can i even shrink entitys? ive tried many different things but i cant get them to shrink

**Comment by gigabit101** [comment]
> Hey sorry for asking but how can i even shrink entitys? ive tried many different things but i cant get them to shrink

Did you try, I don't know right-clicking them?

**Comment by gigabit101** [comment]
> So when it is coming out?

Soon(TM)

**Comment by gigabit101** [comment]
1.1.0 Is now released, https://www.curseforge.com/minecraft/mc-mods/shrink_/files/3352335
