### ISSUE TITLE
Charging

### ISSUE THREAD

**Issue by BellaTheAlphaWolf** [gigabit101/Shrink#25]
I cannot use the shrink device, it keeps telling me it needs to be charged, but when i tried to make the charging table it didn't work. So, I went into creative to check.. and it isn't there! There is no charging table in my game :(

**Comment by gigabit101** [comment]
I do not add a charging station in this mod, You can charge the Shrinking device via any mod that adds RF, If you do not want to do this the RF requirement can be disabled via the config file
