### ISSUE TITLE
The player model is placed too low when riding other entities

### ISSUE THREAD

**Issue by Regnander** [gigabit101/Shrink#27]
What the title says. Riding boats is downright dangerous, since your head is underwater.

| | Normal | Shrunken |
|-|-|-|
| In a boat | ![boat_normal] | ![boat_shrunken] | 
| On a horse | ![horse_normal] | ![horse_shrunken] |

[boat_normal]: https://user-images.githubusercontent.com/17113053/113923002-4de51e00-97e8-11eb-8bd7-c1cbd2c343c9.png
[boat_shrunken]: https://user-images.githubusercontent.com/17113053/113922787-03fc3800-97e8-11eb-918b-04810b378074.png
[horse_shrunken]: https://user-images.githubusercontent.com/17113053/113922788-0494ce80-97e8-11eb-9172-50c8eb848f4b.png
[horse_normal]: https://user-images.githubusercontent.com/17113053/113922790-0494ce80-97e8-11eb-9536-22d1776d5fd7.png

**Comment by gigabit101** [comment]
This is gonna be an issue for almost every entity that can be mounted, compatibility will be added but its very low priority

**Comment by Regnander** [comment]
The only entity I'm really concerned about is the boat since you have to dismount it regularly if you want to avoid drowning.

**Comment by gigabit101** [comment]
Fixed in 1.21
