### ISSUE TITLE
Shrinking every time I or someone goes through Waystones

### ISSUE THREAD

**Issue by PRKRmc** [gigabit101/Shrink#30]
Playing All The Mods 6 in 1.16.5, used the Personal Shrinking Device, now my view height goes to crouch every time I or someone else goes through a Waystone / Dimension 

https://user-images.githubusercontent.com/83446661/116664613-b5fdce80-a966-11eb-86ed-6e163021390d.mp4

**Comment by Feliixtc** [comment]
This is part of issue #11. It has already been flagged as fixed in the version he is bug testing.

**Comment by CritFlaw** [comment]
...how far away are we from 1.10 considering the mod is currently at 1.0.7?

**Comment by gigabit101** [comment]
1.1.0 Is now released, https://www.curseforge.com/minecraft/mc-mods/shrink_/files/3352335
