### ISSUE TITLE
Crash when shrinking and using BudschieMorphMod at the same time in F5

### ISSUE THREAD

**Issue by ZornTaov** [gigabit101/Shrink#31]
Crash Report: https://pastebin.com/0Hs9bzKA
Steps to reproduce:
Morph using BudschieMorphMod into something (I used the Minecraft Fox).
Use the shrinking device from Shrink. to try and become smaller fox.
Go into F5, immediately crash. (also crashes anyone around you in multiplayer)

Linked cross mod issue: https://github.com/Budschie/BudschieMorphMod/issues/3

**Comment by Budschie** [comment]
Ok I've fixed this issue now, so, happy modding everyone, and, if this mod gets updated and new issues arise (which may very well be the case), just open a new issue.
