### ISSUE TITLE
Shrinking device makes x-ray possible

### ISSUE THREAD

**Issue by NillerMedDild** [gigabit101/Shrink#32]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2387

`Shrink-1.16.4-1.0.7`

> **Describe the bug**
> When you shrink yourself and you push yourself into a block you have x-ray and you can see the caves in front of you.
> 
> **Screenshots**
> ![2021-06-09_21 35 10](https://user-images.githubusercontent.com/81689755/121418183-fccde380-c96a-11eb-87c5-f8406c8eb19c.png)

**Comment by gigabit101** [comment]
This is already fixed in 1.1.0

**Comment by NillerMedDild** [comment]
Ah sorry, and thanks 👍
