### ISSUE TITLE
Crash with werewolf models

### ISSUE THREAD

**Issue by HonestAngel** [gigabit101/Shrink#33]
I am sure it is happening because this mod hates anything that isn't minecraft or so it seems. You cannot shrink a Dragon Survival dragon model and now if you shrink while a werewolf it crashes too.

https://www.curseforge.com/minecraft/mc-mods/werewolves-become-a-beast

The second anyone changes to the werewolf form while shrunk crashes with an exit code 1
The reason is java.lang.IllegalStateException: Pose stack not empty

We are all playing on a server and we now cannot use shrink. We loved it and now... everyone is upset...
Here is the crash log that was sent to me from my daughter... She wants it fixed... please
[crash-2021-06-25_13.46.54-client.txt](https://github.com/gigabit101/Shrink/files/6718847/crash-2021-06-25_13.46.54-client.txt)

**Comment by HonestAngel** [comment]
The werewolf is the beast or survivalist form... both cause the crash.

**Comment by HonestAngel** [comment]
Minecraft Version: 1.16.5
Forge: net.minecraftforge:36.1.31

**Comment by gigabit101** [comment]
remove Optifine

**Comment by HonestAngel** [comment]
Ok I removed Optifine and here is the new crash... now what?

Minecraft Version: 1.16.5
Forge: net.minecraftforge:36.1.31
Shrink-1.16.4-1.1.0.jar

java.lang.IllegalStateException: Pose stack not empty

[crash-2021-06-25_23.39.14-client.txt](https://github.com/gigabit101/Shrink/files/6719670/crash-2021-06-25_23.39.14-client.txt)

**Comment by HonestAngel** [comment]
OK now if I need to I can reopen it as a new crash report.

Minecraft Version: 1.16.5
Forge: net.minecraftforge:36.1.31
Shrink-1.16.4-1.1.0.jar
Vampirism-1.16.5-1.8.0-beta.2.jar
Werewolves-1.16.5-1.8-0.5.0.jar 
^ No Other Mods ^

[crash-2021-06-26_00.28.05-client.txt](https://github.com/gigabit101/Shrink/files/6719738/crash-2021-06-26_00.28.05-client.txt)

java.lang.IllegalStateException: Pose stack not empty
