### ISSUE TITLE
my pov is starting from my legs

### ISSUE THREAD

**Issue by OstoraSiraj** [gigabit101/Shrink#34]
I am playing atm6 modpack and i have an issue with my pov: https://streamable.com/7jdxxh
basically its like my eyes are in my legs even with original size (no shrinking), this happened after i updated the modpack to 1.6.11.

**Comment by jeremiahwinsley** [comment]
This seems to happen when upgrading from 1.0.7 to 1.1.0 (possibly while shrunken?). I was able to work around this in a test world by editing level.dat with NBTExplorer and deleting `Data/Player/ForgeCaps/shrink:shrunk`.

**Comment by gigabit101** [comment]
There were some major code changes that could have caused this, Removing your shrink file should resolve this issue.

**Comment by jeremiahwinsley** [comment]
We've suggested that as a workaround, but not all of our players are technologically inclined enough to use an NBT editor. Maybe you could add a button on the GUI, or a command, to reset all shrink data to the defaults?
