### ISSUE TITLE
java.lang.IllegalStateException: Pose stack not empty

### ISSUE THREAD

**Issue by HonestAngel** [gigabit101/Shrink#35]
Minecraft Version: 1.16.5
Forge: net.minecraftforge:36.1.31
Shrink-1.16.4-1.1.0.jar
Vampirism-1.16.5-1.8.0-beta.2.jar
Werewolves-1.16.5-1.8-0.5.0.jar
^ No Other Mods ^

[crash-2021-06-26_00.28.05-client.txt](https://github.com/gigabit101/Shrink/files/6720727/crash-2021-06-26_00.28.05-client.txt)

**Comment by gigabit101** [comment]
My mod is not in this Stacktrace, I have nothing to go on with this log...
Can you please provide me with download links to these mods?

**Comment by HonestAngel** [comment]
https://www.curseforge.com/minecraft/mc-mods/werewolves-become-a-beast/files/3362556
https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire/files/3360347

**Comment by HonestAngel** [comment]
To make it crash level up a werewolf until you unlock either Beast or Survivalist Form. When it is night change into your new form. If you shrink all the way down and then hit F5 to see how small it is the game will crash with "Pose stack not empty".

**Comment by HonestAngel** [comment]
It happened every time I was already shrunk down to the smallest size and if I tried to change to beast or survivalist form while shrunk it would crash once I hit F5 to see what it looks like shrunk down. I think it is only when you press F5. I can run around as a shrunk down werewolf, but I cannot hit F5 to change the camera.
