### ISSUE TITLE
default POV at wrong height

### ISSUE THREAD

**Issue by lukeplechaty** [gigabit101/Shrink#36]
The default POV is at the wrong height plus in constant crouch hight with out holding shift in 1.1.0 on ATM6
![2021-06-27_22 44 31](https://user-images.githubusercontent.com/8196029/123560322-68041c00-d799-11eb-9c2f-c8804a203ea3.png)

**Comment by gigabit101** [comment]
Can't reproduce, Do you have any more info regarding this issue?

**Comment by lukeplechaty** [comment]
iv fix it now i had to edit the .dat file and remove the shrink entries
