### ISSUE TITLE
Crouch bug still present on 1.1.0

### ISSUE THREAD

**Issue by theboo** [gigabit101/Shrink#37]
I haven't been able to find a consistent way to repro this, but the crouch bug from #11  is most definitely still present in 1.1.0. (looks like someone mentioned it is still happening in that issue as well, just posting this for visibility)

The only difference being that now I don't seem to be able to fix it by having someone else shrink and un shrink me, the only fix seems to be closing world, uninstalling shrink, loading the world, then close and reinstall shrink...

**Comment by NillerMedDild** [comment]
May I ask why this issue was closed? :)

**Comment by endorphinrush** [comment]
Also seeing this in 1.1.0

Third person view shows player standing and able to crouch. First person view appears lower to the ground as though crouching but pressing shift to crouch does not change the view.

Enigmatica 6 0.5.4

**Comment by gigabit101** [comment]
try version 1.1.1

**Comment by gigabit101** [comment]
try version 1.1.1
