### ISSUE TITLE
Piglin Crash

### ISSUE THREAD

**Issue by WenXin20** [gigabit101/Shrink#4]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Shrink v1.0.5`
`Rediscovered v1.3.4`

While in creative, I had spawned a Piglin and then I assume the game crashed when the Piglin changed into a Zombified Piglin. The crash report mentions both Shrink and Rediscovered's Pigman. It crashed both the client and the server.
[Crash Report](https://gist.github.com/WenXin20/029c54aaad226ae351b2262f81d48c09)
[Server Crash Report](https://gist.github.com/WenXin20/fcb422e6623365a1cff6fcfb075fae5d)

**Comment by gigabit101** [comment]
Not my side, PLease report to other mod author

**Comment by WenXin20** [comment]
Alright, thanks
