### ISSUE TITLE
shrinking bug

### ISSUE THREAD

**Issue by XplodinNdr08** [gigabit101/Shrink#41]
when i shrink everything is fine until when i go big its fine but when i crouch while big my camera shoots up high when i am barely big and when i shrink everything is fine until when i crouch my camera goes farther down

**Comment by gigabit101** [comment]
What version of the Mod are you using?

**Comment by XplodinNdr08** [comment]
the newest version?

**Comment by gigabit101** [comment]
Version number please, Saying the "newest version" is NOT helpful

**Comment by XplodinNdr08** [comment]
Shrink-1.16.4-1.1.4.jar

**Comment by XplodinNdr08** [comment]
everytime i crouch when im big my camera goes higher up but when im small and i crouch my camera goes down

**Comment by gigabit101** [comment]
hmm, I am not having that issue but I will look into it when I have some free time

**Comment by XplodinNdr08** [comment]
Weird

**Comment by XplodinNdr08** [comment]
yeah its still happening to me even when i dont have mods on other then shrink.

**Comment by XplodinNdr08** [comment]
yeah i chose to do Shrink-1.16.4-1.1.0.jar instead and its working just fine without the bug that is happening on the newest version

**Comment by XplodinNdr08** [comment]
for some reason Shrink-1.16.4-1.1.0.jar is the only version that works :/

**Comment by gigabit101** [comment]
I have tracked down the issue to a change in the changeSize event in Forge in newer versions, I am working on a fix

**Comment by gigabit101** [comment]
Fixed in 1.1.5 https://www.curseforge.com/minecraft/mc-mods/shrink_/files/3392461

**Comment by beaussan** [comment]
Thank you for the quick fix! I was experiencing the same issue =)
