### ISSUE TITLE
Shrinking is putting my point of view inside block.

### ISSUE THREAD

**Issue by Tinytin99** [gigabit101/Shrink#43]
First person before Shrink.
![2021-07-18_18 18 08](https://user-images.githubusercontent.com/87613280/126074652-30cb95c5-a422-48da-9ac9-55e64c2ae31e.png)
Frist person after Shrink.
![2021-07-18_18 18 19](https://user-images.githubusercontent.com/87613280/126074653-49aa91ac-450b-4ba2-8bb2-855279ff49b8.png)
Third person before shrink.
![2021-07-18_18 18 26](https://user-images.githubusercontent.com/87613280/126074655-ed6ca63c-980e-4ba6-b7d5-adcdb87686f2.png)
Third person after shrink.
![2021-07-18_18 18 42](https://user-images.githubusercontent.com/87613280/126074657-d4b1e26c-a505-409b-a523-816eb805bd86.png)

This issue happened after i updated to ATM 6 1.7.0 . It is on a fresh world and i shrink using the tool and not the keybind. It seems to happen with most shrink sizes.

**Comment by gigabit101** [comment]
Fixed in latest version of the mod
