### ISSUE TITLE
Forge Cap "Scale" Sync Bug

### ISSUE THREAD

**Issue by ReeCodes** [gigabit101/Shrink#44]
When using a command to shrink enemies with NBT data, they don't sync the scale of the mob to the client, only the server - they don't shrink for the client. 

Unloading and reloading the chunk will make them sync to the client and make them appear small - therefore fixing the bug.

**Comment by gigabit101** [comment]
This is not an intended feature of the Mod, The entity that is shrunk will need to send a packet to update clients that they have been shrunk, As this is not an issue with the mod I am going to close this issue
