### ISSUE TITLE
Server crashes when trying to undo shrink.

### ISSUE THREAD

**Issue by callumok2004** [gigabit101/Shrink#45]
So, I have made myself.. very large with the device, and when I try to unshrink, my entire server crashes,

![image](https://user-images.githubusercontent.com/35779365/127079743-b704895e-97d2-4248-8693-361d83bb38fa.png)

Crash Log: https://paste.feed-the-beast.com/view/e280a9f9

**Comment by XplodinNdr08** [comment]
i feel your pain

**Comment by gigabit101** [comment]
"ServerHangWatchdog detected that a single server tick took 60.00 seconds"
I assume there is some sort of lighting update happening while changing your size from such a large state, This is why I set a reasonable max size in the config, I can't think of a good way of resolving this issue my side
