### ISSUE TITLE
1.17.1 does not work with mixins loaded

### ISSUE THREAD

**Issue by whatthedrunk** [gigabit101/Shrink#49]
On ATM7 we now use MixinBootstrap so it trys to load some mixin stuff in your mod that is not updated yet. 
https://hastepaste.com/view/6Gbd7
https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap/files/3437402

**Comment by gigabit101** [comment]
Just released a new build this issue should be resolved but note that MixinBootstrap should no longer be needed as of latest version of Forge
