### ISSUE TITLE
Crafting recipe? 

### ISSUE THREAD

**Issue by creepinson** [gigabit101/Shrink#5]
Is there a crafting recipe for personal shrinking device? I don't have jei installed and if there is it would be nice to add it to the curseforge page.

**Comment by creepinson** [comment]
Also, it seems like you can only shrink to a certain size thats hard coded, and I couldn't find any good alternatives that do what i want. Can you make it so that it wraps between a min a and a max size? So then you could do right click it goes up, shift+right click = down. And if it reached the max it would either not work or wrap back around to the min size.

**Comment by gigabit101** [comment]
More options for sizes etc will be coming soon, Mod was released early due to demand.
Use JEI for crafting recipe or get the recipe from https://github.com/gigabit101/Shrink/blob/master/src/generated/resources/data/shrink/advancements/recipes/shrink/shrinking_device.json
