### ISSUE TITLE
Shrink Device Not working

### ISSUE THREAD

**Issue by CanBoy67** [gigabit101/Shrink#50]
I have installed version 1.1.5 of the shrink mod and for some reason when I shift right-click the sound plays but my character doesn't shrink, and after I was supposed to shrink I get a message in the chat that I can't open the shrinking tool while shrunk even though I'm not. I don't know what's going on.

**Comment by CanBoy67** [comment]
nvm figured it out

**Comment by Icantthinkofanam3** [comment]
how did you fix it?

**Comment by Icantthinkofanam3** [comment]
> 

how did you fix it?

**Comment by CanBoy67** [comment]
I just opened the shrink devices gui and chose the size i wanted
