### ISSUE TITLE
View Point After Shrinking

### ISSUE THREAD

**Issue by tehcalipwnt** [gigabit101/Shrink#51]
So I noticed that after I got shrunk my a friend on our Direwolf20 1.16 server that my view point will bug out from time to time.

I will be standing there and my view point will suddenly change as if I am crouching.  It seems to happen most often as I am opening an inventory. My character will not be physically crouching, and pressing the crouch will change my view point. At least 3 other peoples besides me have reporting this problem on the server.

Has anyone else had this problem or have found a fix?

Just realized this problem was report in problem #11, don't see a solution there however.

**Comment by gigabit101** [comment]
Update the mod to the latest version
