### ISSUE TITLE
Walking in render distance of another player causes a teleport

### ISSUE THREAD

**Issue by Pizza4Ever** [gigabit101/Shrink#52]
Issue is that .blockPosition() is a 3xinteger, effectively flooring the xyz values, replacing it with .position() fixes the teleport

**Comment by Pizza4Ever** [comment]
The PacketShrink class should have line 57 be replaced with: `entity.setPos(entity.position().x, entity.position().y, entity.position().z);` or be completely removed

**Comment by gigabit101** [comment]
Fixed in 1.1.6
