### ISSUE TITLE
Option to set a specific entity to render instead of the cow

### ISSUE THREAD

**Issue by Ridanisaurus** [gigabit101/Shrink#54]
When using the mod with Quark in the same pack, and Quark has the variant cow textures active, it causes the Rendered Cow in the Shrink GUI to flash pretty fast which could cause an epileptic seizure. 
Would be nice to have an option to either set a different entity, or a way to stop the entity from cycling its textures.

Mod Version: Shrink-1.16.5-1.1.5.jar
Forge Version: 1.16.5-36.2.4

**Comment by gigabit101** [comment]
This render has been removed in newer versions and is not currently planned on being added back
