### ISSUE TITLE
Captured mob in a bottle is voided when inventory is full

### ISSUE THREAD

**Issue by NielsPilgaard** [gigabit101/Shrink#57]
While having a full inventory, picking up a shrunken mob in a bottle (from a stack of bottles, so it doesn't make space in the inv) will just void the item of the bottled mob.

Relayed  from: https://github.com/NillerMedDild/Enigmatica6/issues/3940

**Comment by Vaeta** [comment]
Silly question, but how do you even capture mobs? Do you have to be regular size yourself? My daughter is playing in Creative mode.

**Comment by gigabit101** [comment]
> 

Right-click on a mob that has been shrunk

**Comment by gigabit101** [comment]
Fixed in 1.3.4
