### ISSUE TITLE
Holding down keybind constantly triggers shrink

### ISSUE THREAD

**Issue by Rodg88** [gigabit101/Shrink#59]
Holding the toggle shrink key will constantly toggle shrink, making the player shrink and unshrink very quickly, instead of just triggering when the key gets pressed initially. It makes it hard to use reliably, you need to be very quick to just toggle your size once.
Shrink-1.16.5-1.1.6, Forge 36.2.21, in Enigmatica 6 modpack

**Comment by gigabit101** [comment]
Fixed in 1.3.4
