### ISSUE TITLE
1x1 open space while shrunk causes entrapment when coming from multipart blocks

### ISSUE THREAD

**Issue by Pants44** [gigabit101/Shrink#6]
Noticed the issue with the swimming animation activating when there is only a one block space. While thats not a big issue to me because its a core minecraft feature, i noticed when coming from a multipart block like a wire you can be entrapped in the single block space. A multipart block being a wire or cable.

Not sure if this is something that can be easily fixed.

**Comment by gigabit101** [comment]
hmm, Not sure how or even if I can fix this but I will look into it.

**Comment by gigabit101** [comment]
Same as #11
