### ISSUE TITLE
Can't shrink GeckoLib mobs

### ISSUE THREAD

**Issue by Rodg88** [gigabit101/Shrink#60]
Mobs that use GeckoLib https://www.curseforge.com/minecraft/mc-mods/geckolib can't be shrunk visually. For example Ars Nouvaeu or Resourseful Bees. The nametag (from quark) seems to move sometimes, and I think the hitbox might get scaled, but nothing visually changes.
Shrink-1.16.5-1.1.6, and for example mobs, ars_nouveau-1.16.5-1.24.14 or ResourcefulBees-1.16.5-0.10.3

**Comment by gigabit101** [comment]
I will have to look at the lib and see how they do the render
