### ISSUE TITLE
Feature Request: Commands to Shrink/Enlarge

### ISSUE THREAD

**Issue by Darkosto** [gigabit101/Shrink#64]
Hey Gigabit!

I was hoping I could use Shrink to add some fun features to Content Creator Integration or random in-game events. Is it possible to have commands to run the shrink/enlarge mechanics too?

MC: 1.18.1
Shrink: 1.3.0
Forge: 39.1.0

Thank you very much!
Darkosto

**Comment by gigabit101** [comment]
I did have commands inside of the mod before but during the porting stage to 1.18 they broke and I didn't have the time to re-enable them, I will see if I can get them back in for the next update

**Comment by Ozphilo** [comment]
I was looking to see if this was an option as well. Look forward to the ability to. Thanks for the fun mod!

**Comment by Quezler** [comment]
+1

**Comment by gigabit101** [comment]
I keep meaning to do this and keep forgetting...

**Comment by Quezler** [comment]
No worries, only noticed it wasn't working because i wanted to upscale my friend and didn't want to press the ^ button 100 times, luckily i discovered it supports scrolling between then and now, so i wouldn't call it a pressing issue for me.  👀
