### ISSUE TITLE
[Enhancements] Various config options & possibly device tier system

### ISSUE THREAD

**Issue by m31317015** [gigabit101/Shrink#68]
Hi, here are a couple of ideas I have in my mind for this mod.

Configs:
- Variables for default player size before and after shrinking
- Option for toggling shrinking devices' recipes and existences
- Option for toggling shrinking devices' behavior (shrink to 1 level and revert, continue shrinking while holding right click & reverse when shifting, toggle through levels if device support multi-level shrinking)
- Option for toggling tiered shrinking devices

Tiered System:
- Different devices based on different materials
- Custom devices based on custom materials with config options
- Fetch block or item textures for devices with custom materials.
- Customized recipes (Well I mean we have Crafttweaker & KubeJS, maybe for toggling recipes of default tiered devices)

Mod compatibility & others:
- Maybe to add the options for using mana from Botania instead of RF or some other kind of magic system?
- Options to enlarge to something like Titans? ;)
- Rendering distance adjustments depending on the size (this will be messy to code I believe)
- Warning message in chat when crafting the first shrinking device in a world.

Hopefully, this helps you develop the mod into something more than a shrinking device, like how morph gave its place back then. Nice work!

**Comment by gigabit101** [comment]
The mod has an api that can be used to add such mechanics. These will not be options in the base mod
