### ISSUE TITLE
Perspective

### ISSUE THREAD

**Issue by JSADwd** [gigabit101/Shrink#7]
Perspective is different. I had a problem where when i shrunk  the perspective would stay the same as the normal two block fp and third person camera.

**Comment by gigabit101** [comment]
Not has this issue, Can I ask if you have another mod installed that does anything to the camera?

**Comment by JSADwd** [comment]
I have a question. does this mod require threecore to operate

**Comment by gigabit101** [comment]
Shrink has no dependencies

**Comment by JSADwd** [comment]
ok thank you. I have another question. how do you charge the controller

**Comment by gigabit101** [comment]
With any block that can charge RF items, If you don't have any power requirements can be disabled via the config
