### ISSUE TITLE
Can't translate Glass Bottle lore

### ISSUE THREAD

**Issue by xMikux** [gigabit101/Shrink#77]
There don't have translate key on ``Glass Bottle`` lore.
It looks like it is hard coded.
![image](https://user-images.githubusercontent.com/26039249/199738678-8b663bd0-c7fc-4f10-bbe8-36f986764fcf.png)

**Comment by gigabit101** [comment]
I will look at updating this later, Can I ask what MC version you are playing?

**Comment by xMikux** [comment]
1.18.2
