### ISSUE TITLE
Softlock

### ISSUE THREAD

**Issue by abraxas** [gigabit101/Shrink#78]
I managed to softlock myself.  I chose "10x" for size and ran the device, which made me a giant.

Inexplicably, wherever I click with the device, I get "Can't open while shrunk" even if I click with it at open air.  At this point, I think my game is softlocked and I'm stuck as a giant who can't do anything.

**Comment by gigabit101** [comment]
Sounds like user error

**Comment by abraxas** [comment]
Which part?  I wasn't trying to open anything, so the device should not have malfunctioned.  Or is that a troll?  I had to warp myself into a brick wall to die because the game wouldn't let the shrinking device trigger again.

**Comment by gigabit101** [comment]
You need to shift-click to change size, device is working fine

**Comment by gigabit101** [comment]
![duh.gif](https://user-images.githubusercontent.com/5615438/201160340-2b55aa15-e650-4026-93c5-78ce328b7743.gif)

**Comment by abraxas** [comment]
@gigabit101 This is not user error, nor is it resolved.  Also, programmer-to-programmer, I'm going through the effort to report this, so I'd rather get more than just a duh.gif and an instant-close.

When you use the Shrinking Device with a target size that's too large, the device stops functioning to return to the same size.  Instead of working, it gives an error about trying to open the UI.

To replicate:

1. Set size to 10x
2. "Shrink" with Shift+Rightclick
3. Now shift-right-click... The Shrinking Device Fails giving the "open" error

Expected results... I should shrink back down.

And for the record, I have replicated it multiple times now.  It only happens when I try to go to a particularly large size, but it locks me 100% of the time until I get my character killed.

**Comment by gigabit101** [comment]
No this is not the issue, the issue is you have already been resized, due to this you can NOT open the gui.

You will need to change back to default size by shift-clicking or using the shrink keybind.

So once again, this is not a bug

**Comment by abraxas** [comment]
Let me reiterate.  I'm trying to change back to the default size.  When I am large, and I shift-rightclick, **I get the same message I would have gotten without holding shift.**  

Here's some context: I'm in stoneblock 3.  It might be caused by the forced-crouch effect of a large size.  It might not.

And I am replicating the issue, consistently.  With lesser shrink Amounts, it works and I"ve been using it for a couple hours.  When my resize is particularly large, only then does it softlock me.  No combination of shift and right-click will trigger the resize for me.  That's the bug I'm reporting.

**Comment by abraxas** [comment]
![image](https://user-images.githubusercontent.com/299146/201163158-03abe1b9-18b4-4e39-98e8-ad2cd8c2d0c5.png)
