### ISSUE TITLE
Allow for smaller min size to work for chisel & bits

### ISSUE THREAD

**Issue by Gorbagegoblin** [gigabit101/Shrink#80]
I know you previously stated that you don't wish to allows players to x-ray so you set a min size, but shouldn't this just be left up to the player themselves or the server owner? Personally, I'd enjoy this mod much more if I could shrink to a smaller size. Is there a way I could edit the code myself to do this personally without you having to change the entire mod? Thanks, in advance.

**Comment by gigabit101** [comment]
Fine, I will remove the minSize limit in the next version

**Comment by gigabit101** [comment]
I have remove the limit, https://www.curseforge.com/minecraft/mc-mods/shrink_/files/4407257

**Comment by Gorbagegoblin** [comment]
Thank you!
