### ISSUE TITLE
Shadows

### ISSUE THREAD

**Issue by Gorbagegoblin** [gigabit101/Shrink#81]
Hey! It's me again, thank you so much for your timely response and update of the mod before! (by far the most thoughtful mod dev)
Now this is not anything that serious, but I think it would be cool if the shadow of the entity also scaled with the size they turn to so as to help make it more realistic. Just a thought!

**Comment by gigabit101** [comment]
Entity shadow size is called from one static value, If I edit this value all player's shadows change...

**Comment by Gorbagegoblin** [comment]
Oh, that's a shame. Thanks for letting me know 👍

**Comment by gigabit101** [comment]
Looked into this again last night, Without some heavy mixins I'm not sure I can fix this, Will continue to poke at it

**Comment by gigabit101** [comment]
This will be available in the 2.0 release of Minecraft 1.20.2
