### ISSUE TITLE
Feature Request: Dynamic FOV Change (Possibly with Auto-Cinematic) when shrinking/enlarging

### ISSUE THREAD

**Issue by osirisgothra** [gigabit101/Shrink#82]
I find that when shrinking, changing the FOV makes the new size "feel" even more realistic, so I sometimes do it manually after shrinking especially if I am going to stay small/large for a while.

Thought that it might be kinda cool if you could have it set the FOV automatically. Of course, the feature could be turned on/off and exact FOV's configured (with whatever you would want the defaults to be) if needed. 

In cases where the FOV is small, the cinematic camera toggle could be automatically enabled/disabled so the screen isn't moving super-fast, if that is even possible (not terribly important, though).

Just a thought, nice mod though, keep up the good work!

**Comment by gigabit101** [comment]
currently I have no interest in changing the players FOV, I already dislike the changes in FOV from other mods/potion effects
