### ISSUE TITLE
[Suggestion] Use the Pehkui library

### ISSUE THREAD

**Issue by ChloeDawn** [gigabit101/Shrink#83]
Mod version: [1.19-1.3.5](https://www.curseforge.com/minecraft/mc-mods/shrink_/files/4407257)

Pehkui is a library for Forge and Fabric that implements scale changing well, including support for automatically modifying movement speed, interaction reach, step assist, and third-person camera distancing based on the scale. Currently Shrink lacks all of these features and adopting the library would indirectly implement them, along with a handful of other bug fixes.

Link to the library source: <https://github.com/Virtuoel/Pehkui>

If this is not something you have the time for, I can make a pull request to implement it!

**Comment by gigabit101** [comment]
Shrink will gain most of these abilities however I have no interest in using a third-party API to do so
