### ISSUE TITLE
1.20.1 Forge Incompatibility 

### ISSUE THREAD

**Issue by Duxtorm** [gigabit101/Shrink#88]
Hey!
I recently updated my forge version in 1.20.1 and found that Shrink kept crashing the game, so I did some troubleshooting and found a weird incompatibility.

Using Shrink with any version of forge after 47.1.5 (47.1.6 - 47.1.28) causes this error:

```
The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'float net.minecraftforge.event.entity.EntityEvent$Size.getNewEyeHeight()'
```

Crash report: https://pastebin.com/FbKUchki
Log: https://pastebin.com/9SqMUr94

**Comment by gigabit101** [comment]
Yay for Forge pushing breaking changes in release versions...

**Comment by Duxtorm** [comment]
> Yay for Forge pushing breaking changes in release versions...

;w; I am sorry this is happening-

**Comment by gigabit101** [comment]
Looking at the Forge changelog they readded this in 47.1.29, Updating Forge should fix this crash

**Comment by Duxtorm** [comment]
Oh-
No is still broken '^'

**Comment by gigabit101** [comment]
I will try and take a look at it tonight

**Comment by gigabit101** [comment]
Going to take a look at this now, Let's see what they broke...

**Comment by gigabit101** [comment]
Ok, so they moved the eye height to its own event, Easy fix. New build on CurseForge soon :)

**Comment by gigabit101** [comment]
And its out https://legacy.curseforge.com/minecraft/mc-mods/shrink_/files/4651706

**Comment by Duxtorm** [comment]
> And its out https://legacy.curseforge.com/minecraft/mc-mods/shrink_/files/4651706

Haha, woohoo! Thank you very much for the patch! ♥
