### ISSUE TITLE
Entity NBT resets when releasing an entity on a Create Seat

### ISSUE THREAD

**Issue by MuteTiefling** [gigabit101/Shrink#90]
I had honestly thought this was reported some time ago, as it affected mobs in 1.16 as well. 

It goes like this:

1. Bottle a villager with trades locked in
2. Release said villager by sneak right clicking a Create Seat
3. The villager now has been reset and may pick up a new job/trades
4. Repeat

This apparently works with any mob. For example, the Questing Ram in Twilight Forest similarly gets reset, allowing one to trade with it endlessly. 

Mod Version: Shrink-1.19-1.3.5

**Comment by gigabit101** [comment]
NBT is added back when spawning the entity from the bottle, No idea why its not working for you as its working fine for me
