### ISSUE TITLE
The cow in the preview changes textures wildly

### ISSUE THREAD

**Issue by aaronhowser1** [gigabit101/Shrink#91]
https://github.com/gigabit101/Shrink/assets/15698722/7c3b4f24-9b96-4156-99a5-3cf0c5bd663f

This is possibly because Quark is installed, and it adds randomized mob textures?

Why is there even a cow there? It doesn't change size or anything. Actually, why is the player there either?

Shrink-1.19-1.3.5

**Comment by gigabit101** [comment]
It used to render the size changes, Seems like it broke and yes the cow is because of quark, I have a fix in mind just not released yet, Will look into it tonight

**Comment by gigabit101** [comment]
Fixed in latest 1.20 release
