### ISSUE TITLE
Issue starting Forge 1.20.1 with Shrink-1.20.1-1.4.2.jar

### ISSUE THREAD

**Issue by Mjolinir** [gigabit101/Shrink#93]
Hello!

Error when starting Forge 1.20.1-47.1.3 with Shrink-1.20.1-1.4.2.jar:

Shrink (shrink) has failed to load correctly
java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/EntityEvent$EyeHeight

I tried to update to Shrink-1.20.1-1.4.3.jar but it requires a higher version of Forge than I can currently run with other mods.

**Comment by gigabit101** [comment]
You will need to use Shrink-1.20-1.4.1.jar for older Forge versions

**Comment by Mjolinir** [comment]
Excellent! I will do this. Shrink-1.20-1.4.1.jar does not seem to be available on Curseforge. I will look for it. Thank you.

**Comment by gigabit101** [comment]
https://www.curseforge.com/minecraft/mc-mods/shrink_/files/4576062

**Comment by gigabit101** [comment]
I just updated the file to allow 1.20.1, This will take some time to show up on the Curse app

**Comment by Mjolinir** [comment]
Thank you! Thank you for the mod, as well!
