### ISSUE TITLE
shrink not working and config tab greyed out

### ISSUE THREAD

**Issue by cherriekae** [gigabit101/Shrink#94]
I downloaded the 1.20.1 Release version through Forge and used the personal shrinking device but nothing happened. The only thing that changed was the size of my avatar in the inventory tab, and I even went into the GUI scale with the cow to shrink but nothing worked. What do I do?

**Comment by gigabit101** [comment]
What Forge version are you using?

**Comment by cherriekae** [comment]
I'm using Forge 47.1.46

**Comment by cherriekae** [comment]
Hello?

**Comment by gigabit101** [comment]
Use the config file to edit the settings, mod works fine in testing. Right click to open ui, shift right click to use 

Note it requires RF power unless it's turned off in the config file
