### ISSUE TITLE
Dedicated Server on launch crash. 

### ISSUE THREAD

**Issue by Zelioth** [gigabit101/Shrink#96]
Attempting to use this on client and server side. 

Minecraft 1.20.1
Forge 47.2.0
shrink 1.4.3

Appears when you include this in a server environment it gives this error 

   Mod File:  /Shrink-1.20.1-1.4.3.jar
        Failure message: Shrink (shrink) has failed to load correctly
                java.lang.reflect.InvocationTargetException: null
        Mod Version: 1.4.3
        Mod Issue URL: NOT PROVIDED
        Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/entity/EntityRenderer for invalid dist DEDICATED_SERVER

And when attempting to connect to the server with Shrink disabled it says that the server is missing the mod shrink |

Server Crash 
https://gist.github.com/Zelioth/1434085be1addb29d5a2efa073e2f978

![Screenshot 2023-09-30 213229](https://github.com/gigabit101/Shrink/assets/77481431/7c9e2370-2d44-422b-ac18-90e7c399f20d)

**Comment by Zelioth** [comment]
Looks like Using version 1.4.2 in server and client allows it to load perfectly. but 1.4.3 does not allow server to launch or client to connect without it being in server.

**Comment by gigabit101** [comment]
Can I get the full crash log?

**Comment by Zelioth** [comment]
Full crash log? The crash log I provided was the full server crash log on startup. Removing shrink or downgrading it fixes the issue. The client isn’t crashing it’s just refusing to connect to server without shrink installed or downgraded

**Comment by gigabit101** [comment]
Fixed in 1.4.4 https://legacy.curseforge.com/minecraft/mc-mods/shrink_/files/4784393
