### ISSUE TITLE
Camera not functioning

### ISSUE THREAD

**Issue by HappyChick3n** [gigabit101/Shrink#97]
Using the shrinking device on a player doesn't change their camera height to match their new size.

**Comment by gigabit101** [comment]
Minecraft version?
Forge Version?
Modpack?

This works fine in and outside of dev so I am going to assume this is an issue caused by another mod

**Comment by HappyChick3n** [comment]
Minecraft version 1.20.1, forge version 47.2.1, I've tried running the mod with only an FE generation mod installed alongside it but i still run into the same issue

Edit: Running the mod entirely on it's own still causes the issue

**Comment by gigabit101** [comment]
hmm, not able to reproduce this might be the forge version I am using in dev, Can I ask what version of Shrink you are using?

**Comment by HappyChick3n** [comment]
1.4.3

**Comment by gigabit101** [comment]
Thanks, Going to update forge in dev and see what broke

**Comment by gigabit101** [comment]
Yeah, It was a forge change, Pushed a Fix and should be up on CurseForge in the next few minutes

**Comment by gigabit101** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/shrink_/files/4784393

**Comment by HappyChick3n** [comment]
ty :)

**Comment by gigabit101** [comment]
np
