### ISSUE TITLE
1.20 Player View Not Changing

### ISSUE THREAD

**Issue by MichaelMichelle2** [gigabit101/Shrink#98]
I recently created a new modpack and the player camera isn't moving down at all, so in small spaces I cant see unless I crouch, which isn't ideal for create.

**Comment by gigabit101** [comment]
Minecraft version?
Mod version?
Forge or Neoforge?

**Comment by MichaelMichelle2** [comment]
Minecraft version 1.20.1, Minecraft Forge version 47.2.0, and mod version is 1.4.4

**Comment by MichaelMichelle2** [comment]
> Minecraft version? Mod version? Forge or Neoforge?

The error still persists when I update my mods, I haven't tried it solo yet to see if its an issue with another mod or not, but none of my mods should mess with the camera.

**Comment by gigabit101** [comment]
Version 1.4.4 was built using Forge 47.2.1 due to a Forge change causing a crash, You might need to use 1.4.3 for older Forge versions

**Comment by MichaelMichelle2** [comment]
> Version 1.4.4 was built using Forge 47.2.1 due to a Forge change causing a crash, You might need to use 1.4.3 for older Forge versions

I tried downgrading the mod and upgrading forge version, still issue.

**Comment by MichaelMichelle2** [comment]
I forgot to say it only works when crouching

**Comment by gigabit101** [comment]
Not sure why this is happening to you, it works fine for me so guessing it's being caused by another mod

**Comment by MichaelMichelle2** [comment]
> Not sure why this is happening to you, it works fine for me so guessing it's being caused by another mod

Should I test all the mods with the shrink mod one at a time to see what mod it is so you could potentially fix it?

**Comment by gigabit101** [comment]
If another mod is messing with the camera there is nothing I can do about it

**Comment by MichaelMichelle2** [comment]
If its a mod with an open code you probably could. Tho none of the mods I use add anything to the camera that I know of.

**Comment by gigabit101** [comment]
The mod breaking the perspective is Alex's Caves

**Comment by gigabit101** [comment]
Fixed, The New build will be on CurseForge in the next few minutes
