### ISSUE TITLE
[Issue] Wrong perspective

### ISSUE THREAD

**Issue by KayZiomalek** [gigabit101/Shrink#99]
When I use the shrink mod on myself or my friends we have deafult size perspective on the different sized and only holding shift sets the correct perspective.

Modlist:
[modlist.txt](https://github.com/gigabit101/Shrink/files/13329321/modlist.txt)

Ingame I only have backpack in the curio slot.

**Comment by gigabit101** [comment]
Forge or NeoForge?
*Forge version?
Shrink version?

**Comment by KayZiomalek** [comment]
Forge forgot to add
47.2.1

**Comment by gigabit101** [comment]
Still going to need the version numbers

**Comment by KayZiomalek** [comment]
just updated the comment but just incase
Minecraft 1.20.1
Forge 47.2.1

**Comment by gigabit101** [comment]
It's working just fine for me 
![image](https://github.com/gigabit101/Shrink/assets/5615438/e6a42d9b-72cd-4bdc-b3a1-ee58ca415730)

![image](https://github.com/gigabit101/Shrink/assets/5615438/70a706be-3d12-480c-a23b-c99eddbab6d2)

**Comment by KayZiomalek** [comment]
:/ great now i can have fun looking throu the list what mod hates shrink mod for a sec I thought it would be shaders from oculus but nope, maybe attribute fix? well f me but thx anyways

**Comment by gigabit101** [comment]
Shrink does not use attribute so I don't think so, I would look at anything that adds "poses" or maybe player animations

**Comment by gigabit101** [comment]
If you find out what it is please do let me know so I can see if I can patch it

**Comment by KayZiomalek** [comment]
alright will do

**Comment by gigabit101** [comment]
Would you be interested in using a test build if I give you one? Just to help figure out what is going on?

**Comment by KayZiomalek** [comment]
I think I am good I going with the old reliable of disabling mod and seeing which one doesnt like shrink and it is easy thx to curseforge launcher

**Comment by KayZiomalek** [comment]
The mod breaking the perspective is Alex's Caves

**Comment by gigabit101** [comment]
Odd, Thanks for letting me know

**Comment by gigabit101** [comment]
Yup, It sure it
https://github.com/AlexModGuy/AlexsCaves/blob/af46fbd0ac546744f7f620c797db9b885a75e04d/src/main/java/com/github/alexmodguy/alexscaves/server/event/CommonEvents.java#L74

**Comment by KayZiomalek** [comment]
I wonder for why it resets the height, atleast I found a incompability so I wish GL on fixing (if it is possible)

**Comment by gigabit101** [comment]
Yup, Thinking of a good way of handling this

**Comment by gigabit101** [comment]
So, Wanna test a "fixed" build for me?

**Comment by gigabit101** [comment]
Fixed, The New build will be on CurseForge in the next few minutes

**Comment by KayZiomalek** [comment]
Didnt see you answer ye let me check

**Comment by KayZiomalek** [comment]
WORKS just fine now ty for the fix :D

**Comment by gigabit101** [comment]
Perfect, Thanks for tracking down the mod that did it :D
